### ISSUE TITLE
CRASH: Starting a song from a Favorited Show

### ISSUE THREAD

**Issue by arougthopher** [alecgorge/PhishOD-iOS#100]
If I try to play a song from the setlist for a show that has been favorited, it hangs and eventually crashes.
If I look for the song by finding it through Artist->Year->Date it works.

Also, if I go to settings while in the Favorited area, and try to report a bug, it crashes :-)

**Comment by alecgorge** [comment]
Thanks for reporting this! I have fixed this in the next version of Relisten and hopefully it will get approved by Apple soon!

**Comment by arougthopher** [comment]
I will try again, but, did you even try to reproduce?  You just closed the issue!!  Pretty crappy customer support!

**Comment by arougthopher** [comment]
Oops, sorry, wrong bug report :-)
