### ISSUE TITLE
Sonos Open API

### ISSUE THREAD

**Issue by mcromain1021** [alecgorge/PhishOD-iOS#122]
I reached out to Sonos. They have an open API that anyone can build with. Site is located at http://musicpartners.sonos.com/
This would be huge!

**Comment by tamarch** [comment]
I second this request!!

**Comment by Maine110** [comment]
Definitely a stron third for this feature.  So many of us are now using Sonos it would be great to have a direct connection to the sonos system.  Granted we can hard wire to a reliever on a sonos system, but that kind of defeats the purpose.  Thanks for considering!

**Comment by liglehart** [comment]
http://musicpartners.sonos.com/?q=node/21

Ditto. PLEASE PLEASE PLEASE add Relisten to the Sonos music community

**Comment by alecgorge** [comment]
An early iteration: https://github.com/RelistenNet/relisten_sonos#sonos-setup

Follow that repo/file issues there for updates :)

**Comment by liglehart** [comment]
Thanks!

**Comment by mcromain1021** [comment]
It works! Awesome. Thank you so much.
