### ISSUE TITLE
Issues with songs playing

### ISSUE THREAD

**Issue by jdrawas** [alecgorge/PhishOD-iOS#157]
When I try to listen to a show, 2 issues happen. First, once a song is finished, it doesn’t continue to the next song. So I have to manually start a song each time. Secondly, the songs are randomly played, rather than just going in order. Thanks for any help with this!

**Comment by alecgorge** [comment]
Sorry about these issues! I have been working on an upgraded app. You can see the progress in [RelistenNet/relisten-ios](https://github.com/relistennet/relisten-ios). That repo will serve as the baseline for both the new versions of Relisten and PhishOD.

If you like living on the edge, you can sign up to be part of the betas for the new iOS app here: https://beta.relisten.live/ . Playback, browsing and offline is much improved but there are still plenty of bugs and confusing parts.

I have been traveling for the past several weeks so there hasn't been a ton of progress super recently, but it is imminent—I promise!
