### ISSUE TITLE
Can't Read Entire Show Date  on iPhone 5s

### ISSUE THREAD

**Issue by Tsac77** [alecgorge/PhishOD-iOS#88]
I can only see the year and month of every show listed when using my iPhone 5s. For example "2000-10..." is all I can see for every single October 2000 show. Please fix this as finding specific shows is very difficult. I can send you a screenshot of the issue if that will help. Thanks.

**Comment by alecgorge** [comment]
sorry about this. is is fixed in the beta and for the next version

**Comment by Tsac77** [comment]
Thank you so much!

---Tim
